### PR TITLE
Adjust HP system to match more to original game

### PR DESCRIPTION
**Pull request by AlberttFrgk**
reference from @leongkat 
https://discord.com/channels/567996940374245376/1086492322226782329/1158388829837860924
video from DP_

### CODE REVIEW

**Comment by Estrol** [comment]
> reference from @leongkat https://discord.com/channels/567996940374245376/1086492322226782329/1158388829837860924 video from DP_

I don't see any code reference in PR from that discord comment, can you elaborate?

**Comment by AlberttFrgk** [comment]
> > reference from @leongkat https://discord.com/channels/567996940374245376/1086492322226782329/1158388829837860924 video from DP_
> 
> I don't see any code reference in PR from that discord comment, can you elaborate?

It just reference, like how the animation works, i just try to make it similar

**Comment by AlberttFrgk** [comment]
It's in fix(gameplayscene)

**Comment by AlberttFrgk** [comment]
> This is still unfinished one the next commit is the very good one

LOL ITS ALREADY GOOD

**Review by Estrol — APPROVED** [review]

**Pull request merged**
